### ISSUE TITLE
Streaming interface

### ISSUE THREAD

**Issue by sindresorhus** [sindresorhus/strip-json-comments#1]
It's Node, so why not. And should be fairly easy.

**Comment by TCB13** [comment]
As long as the current interface is still available it would be nice! And... I just noticed this package you made, https://github.com/sindresorhus/gulp-strip-json-comments. Seems to fix the streaming interface "issue". Why is this still open?

**Comment by sindresorhus** [comment]
It would be in addition to the current API. The gulp plugin just wraps the current API and is not actually streaming.

**Comment by stevemao** [comment]
@sindresorhus Just wondering how hard do you think this is? This is something I'd always like to learn when I started doing node :) Couldn't understand the complex streaming modules out there so I'd like to see some basic ones :)

**Comment by stevemao** [comment]
@sindresorhus for learning purposed, is there a repo you'd recommend?

**Comment by sindresorhus** [comment]
https://github.com/dominictarr/JSONStream

**Comment by stevemao** [comment]
Thanks. The code seems to be really hard to understand though.
