### ISSUE TITLE
Improve performance

### ISSUE THREAD

**Issue by sindresorhus** [sindresorhus/strip-json-comments#11]
Probably a lot that could be improved performance wise.

**Comment by slauyama** [comment]
Have you thought about serving up a minified version of index.js? Running the current code through http://closure-compiler.appspot.com/home was able to give me about a 60% speed improvement.

[Link with your code inputed](http://closure-compiler.appspot.com/home#code%3D%252F%252F%2520%253D%253DClosureCompiler%253D%253D%250A%252F%252F%2520%2540compilation_level%2520SIMPLE_OPTIMIZATIONS%250A%252F%252F%2520%2540output_file_name%2520default.js%250A%252F%252F%2520%253D%253D%252FClosureCompiler%253D%253D%250A%250A%252F%252F%2520ADD%2520YOUR%2520CODE%2520HERE%250A'use%2520strict'%253B%250Aconst%2520singleComment%2520%253D%25201%253B%250Aconst%2520multiComment%2520%253D%25202%253B%250Aconst%2520stripWithoutWhitespace%2520%253D%2520()%2520%253D%253E%2520''%253B%250Aconst%2520stripWithWhitespace%2520%253D%2520(str%252C%2520start%252C%2520end)%2520%253D%253E%2520str.slice(start%252C%2520end).replace(%252F%255CS%252Fg%252C%2520'%2520')%253B%250A%250Amodule.exports%2520%253D%2520(str%252C%2520opts)%2520%253D%253E%2520%257B%250A%2509opts%2520%253D%2520opts%2520%257C%257C%2520%257B%257D%253B%250A%250A%2509const%2520strip%2520%253D%2520opts.whitespace%2520%253D%253D%253D%2520false%2520%253F%2520stripWithoutWhitespace%2520%253A%2520stripWithWhitespace%253B%250A%250A%2509let%2520insideString%2520%253D%2520false%253B%250A%2509let%2520insideComment%2520%253D%2520false%253B%250A%2509let%2520offset%2520%253D%25200%253B%250A%2509let%2520ret%2520%253D%2520''%253B%250A%250A%2509for%2520(let%2520i%2520%253D%25200%253B%2520i%2520%253C%2520str.length%253B%2520i%252B%252B)%2520%257B%250A%2509%2509const%2520currentChar%2520%253D%2520str%255Bi%255D%253B%250A%2509%2509const%2520nextChar%2520%253D%2520str%255Bi%2520%252B%25201%255D%253B%250A%250A%2509%2509if%2520(!insideComment%2520%2526%2526%2520currentChar%2520%253D%253D%253D%2520'%2522')%2520%257B%250A%2509%2509%2509const%2520escaped%2520%253D%2520str%255Bi%2520-%25201%255D%2520%253D%253D%253D%2520'%255C%255C'%2520%2526%2526%2520str%255Bi%2520-%25202%255D%2520!%253D%253D%2520'%255C%255C'%253B%250A%2509%2509%2509if%2520(!escaped)%2520%257B%250A%2509%2509%2509%2509insideString%2520%253D%2520!insideString%253B%250A%2509%2509%2509%257D%250A%2509%2509%257D%250A%250A%2509%2509if%2520(insideString)%2520%257B%250A%2509%2509%2509continue%253B%250A%2509%2509%257D%250A%250A%2509%2509if%2520(!insideComment%2520%2526%2526%2520currentChar%2520%252B%2520nextChar%2520%253D%253D%253D%2520'%252F%252F')%2520%257B%250A%2509%2509%2509ret%2520%252B%253D%2520str.slice(offset%252C%2520i)%253B%250A%2509%2509%2509offset%2520%253D%2520i%253B%250A%2509%2509%2509insideComment%2520%253D%2520singleComment%253B%250A%2509%2509%2509i%252B%252B%253B%250A%2509%2509%257D%2520else%2520if%2520(insideComment%2520%253D%253D%253D%2520singleComment%2520%2526%2526%2520currentChar%2520%252B%2520nextChar%2520%253D%253D%253D%2520'%255Cr%255Cn')%2520%257B%250A%2509%2509%2509i%252B%252B%253B%250A%2509%2509%2509insideComment%2520%253D%2520false%253B%250A%2509%2509%2509ret%2520%252B%253D%2520strip(str%252C%2520offset%252C%2520i)%253B%250A%2509%2509%2509offset%2520%253D%2520i%253B%250A%2509%2509%2509continue%253B%250A%2509%2509%257D%2520else%2520if%2520(insideComment%2520%253D%253D%253D%2520singleComment%2520%2526%2526%2520currentChar%2520%253D%253D%253D%2520'%255Cn')%2520%257B%250A%2509%2509%2509insideComment%2520%253D%2520false%253B%250A%2509%2509%2509ret%2520%252B%253D%2520strip(str%252C%2520offset%252C%2520i)%253B%250A%2509%2509%2509offset%2520%253D%2520i%253B%250A%2509%2509%257D%2520else%2520if%2520(!insideComment%2520%2526%2526%2520currentChar%2520%252B%2520nextChar%2520%253D%253D%253D%2520'%252F*')%2520%257B%250A%2509%2509%2509ret%2520%252B%253D%2520str.slice(offset%252C%2520i)%253B%250A%2509%2509%2509offset%2520%253D%2520i%253B%250A%2509%2509%2509insideComment%2520%253D%2520multiComment%253B%250A%2509%2509%2509i%252B%252B%253B%250A%2509%2509%2509continue%253B%250A%2509%2509%257D%2520else%2520if%2520(insideComment%2520%253D%253D%253D%2520multiComment%2520%2526%2526%2520currentChar%2520%252B%2520nextChar%2520%253D%253D%253D%2520'*%252F')%2520%257B%250A%2509%2509%2509i%252B%252B%253B%250A%2509%2509%2509insideComment%2520%253D%2520false%253B%250A%2509%2509%2509ret%2520%252B%253D%2520strip(str%252C%2520offset%252C%2520i%2520%252B%25201)%253B%250A%2509%2509%2509offset%2520%253D%2520i%2520%252B%25201%253B%250A%2509%2509%2509continue%253B%250A%2509%2509%257D%250A%2509%257D%250A%250A%2509return%2520ret%2520%252B%2520(insideComment%2520%253F%2520strip(str.substr(offset))%2520%253A%2520str.substr(offset))%253B%250A%257D%253B%250A)

Also another way I was able to get some speed improvements by making a variable called `combinedChar` and setting it to `currentChar + nextChar`
