### ISSUE TITLE
Breaks Regular Expressions

### ISSUE THREAD

**Issue by sibedge** [sindresorhus/strip-json-comments#26]
Examples of valid RegExp that gets broken:

```js
// thinks it is a text opening:
/'/
/"/
/\`/
```

```js
// thinks it is a single-line comment opening:
/\//
```

```js
// thinks it is a multi-line comment opening:
/\/*/
```

**Comment by SamVerschueren** [comment]
I tested this but can't seem to reproduce. I tested following cases

```js
	t.is(fn('{"a":/\//}'), '{"a":/\//}');
	t.is(fn('{"a":/\/*/}'), '{"a":/\/*/}');
	t.is(fn('{"a":/\'/}'), '{"a":/\'/}');
	t.is(fn('{"a":/"/}'), '{"a":/"/}');
	t.is(fn('{"a":/\`/}'), '{"a":/\`/}');
```

Can you provide a json example that doesn't work with you?

**Comment by sibedge** [comment]
Even if we follow the example on the main page, and change it to:

```js
{
    // rainbows
    "unicorn": /'/
}
```

that already breaks.

**Comment by sindresorhus** [comment]
@sibedge That's not valid JSON even without the comment. You can't use regex literals in JSON.

**Comment by sibedge** [comment]
So in other words, this library only works with simplified JSON, but is incapable of processing general JavaScript. I would suggest then to mention it on the main page, because it wasn't clear.

**Comment by sindresorhus** [comment]
There's no "simplified JSON", it's either JSON or it's not. JSON is not JS. The readme is already very clear about it stripping comments in JSON.

**Comment by sibedge** [comment]
There is simplified JSON, which is the one that doesn't support open property names: `{name: "value"}`. 

Your code works only with `{"name":"value"}`.

**Comment by sindresorhus** [comment]
No, that's a JavaScript object literal.

```
