### ISSUE TITLE
Include LICENSE file

### ISSUE THREAD

**Issue by chrisrecher** [sindresorhus/strip-json-comments#29]
I'm in a corporate environment and would love to use this package, but cannot due to the lack of a LICENSE file. Please consider adding one containing the license text and your copyright?

**Comment by sindresorhus** [comment]
https://github.com/sindresorhus/strip-json-comments/blob/master/license

**Comment by chrisrecher** [comment]
Wonderful, thanks a ton! Any chance of this getting pushed to NPM?

**Comment by sindresorhus** [comment]
@chrisrecher I didn't do anything. I was pointing out it's already there (and in the npm package).
