### ISSUE TITLE
We added require hook

### ISSUE THREAD

**Issue by bahmutov** [sindresorhus/strip-json-comments#3]
In this wrapper https://github.com/uTest/autostrip-json-comments

``` javascript
require('autostrip-json-comments');

var obj = require('path/to/commented-json-filename');
// comments are automatically stripped inside require
```

**Comment by SamVerschueren** [comment]
Hi @sindresorhus, is there any reason why the mention is removed from the readme in commit https://github.com/sindresorhus/strip-json-comments/commit/9156df0f201bdd9a8aa76df94344d2a678a3635e? Or was it just to clean up the readme file?

**Comment by SamVerschueren** [comment]
Okay, it seems the library uses a very old version (`0.1.3`) of this library.

**Comment by sindresorhus** [comment]
@SamVerschueren require hooks are pretty bad practise so I didn't feel comfortable recommending it.

**Comment by SamVerschueren** [comment]
Oh ok, thanks for the tip :). How would you recommend loading them in?

Something like this?
```js
var config = JSON.parse(stripJsonComments(fs.readFileSync('./config.json')));
```
