### ISSUE TITLE
Add a configuration or parameter to change one line comment pattern and multiline comment pattern

### ISSUE THREAD

**Issue by hemavidal** [sindresorhus/strip-json-comments#31]
I want to change the comment pattern to **#** as python comment!

Can you change the package comment pattern to be configurable?

**Comment by sindresorhus** [comment]
No, that's outside the scope of this module. Check out https://hjson.org/. It's supports `#` comments.

**Comment by hemavidal** [comment]
Ok Thanks a lot! Hjson woks fine to me!
