### ISSUE TITLE
Error on install

### ISSUE THREAD

**Issue by danielgalleni** [sindresorhus/strip-json-comments#35]
On install show this error:
npm WARN tar ENOENT: no such file or directory, open '/home/ionic-app/node_modules/.staging/ajv-0fc645a4/dist/ajv.min.js.map'
npm ERR! path /home/ionic-app/node_modules/.staging/fined-2cea2c09/node_modules/tar
npm ERR! code ENOENT
npm ERR! errno -2
npm ERR! syscall rename
npm ERR! enoent ENOENT: no such file or directory, rename '/home/ionic-app/node_modules/.staging/fined-2cea2c09/node_modules/tar' -> '/home/ionic-app/node_modules/.staging/tar-1bf39489'
npm ERR! enoent This is related to npm not being able to find a file.
npm ERR! enoent
npm ERR! A complete log of this run can be found in:
npm ERR!     /home/.npm/_logs/2018-05-27T23_03_51_754Z-debug.log

**Comment by sindresorhus** [comment]
Can't reproduce this and it doesn't look related to this module.

Use https://github.com/npm/npm for npm support.
