### ISSUE TITLE
Stripping trailing part of "s/foo//" regex inside doubly-escaped script value breaks existential ssh command

### ISSUE THREAD

**Issue by broofa** [sindresorhus/strip-json-comments#36]
This is that issue you've been dreading, I'm afraid.  Apologies in advance.

So, I have this terrible `script` command in my `package.json` file.  It runs `tail` via `ssh`, and pipes it through `sed` to do some higgerty-piggerty shit to prettify the output.  The `sed` command has a wonky regex to strip off the ISO time prefix because, hey, time is just an artificial construct that devalues our all-too-ephemeral existence in this sad, sad, world.

It's awful, I know.  Don't judge me.

The problem?  ESLint no longer works because ESLint is trying to be clever and read my `package.json` even though there's nothing relevant to ESLint there but, hey, thanks for being clever.  It barfs because `SyntaxError: Cannot read config file: .../package.json`.

Yay! 😹 

Anyhow, the problem boils down to [to this bit o' code](https://github.com/eslint/eslint/blob/caeb223c4f7b0b6fe35e5348ae0df4c6446b5bed/lib/config/config-file.js#L114), wherein my perfectly valid `package.json` file gets garbage-ified before being handed to `JSON.parse`.

Here's the SSCCE ...

`package.json`:
```
{
  "scripts": {
    "tail": "ssh some_host \"tail -f some_file | sed -e \\\"s/^.\\\\{46\\\\}T//\\\" -e \\\"s/#033/\\\\x1b/g\\\"\""
  }
}
```

Then...

```
node -e "console.log(require('strip-json-comments')(require('fs').readFileSync('package.json', 'utf8')))"
```

Output:

```
{
  "scripts": {
    "tail": "ssh some_host \"tail -f some_file | sed -e \\\"s/^.\\\\{46\\\\}T                                     
  }
}
```

**Comment by broofa** [comment]
FWIW, I've temporarily worked around this by changing the `...\}T//...` regex to `...\}T/\/...`.

**Comment by sindresorhus** [comment]
I don't have time to look at it right now, but I added a failing test.
