### ISSUE TITLE
You can try this

### ISSUE THREAD

**Issue by luojianet** [sindresorhus/strip-json-comments#38]
```sftp-config.json
{  
  "connect_timeout": 30,
    //"keepalive": 120,
    //"ftp_passive_mode": true,
    //"ftp_obey_passive_host": false,
    //"ssh_key_file": "~/.ssh/id_rsa",
    //"sftp_flags": ["-F", "/path/to/ssh_config"],

    //"preserve_modification_times": false,
    //"remote_time_offset_in_hours": 0,
    "remote_encoding": "GBK",
    //"remote_locale": "C",
    //"allow_config_upload": false,
}
```

result
```
{
    "connect_timeout": 30,








    "remote_encoding": "GBK",


}
```

at last have a  comma。after`"GBK"`

**Comment by ArtskydJ** [comment]
I would not consider this a bug with `strip-json-comments`.

---

### option 1 - leading commas

Another option is to use leading commas.
```
{
    "connect_timeout": 30
    //, "keepalive": 120
    , "remote_encoding": "GBK"
    //, "allow_config_upload": false
}
```
result:
```json
{
    "connect_timeout": 30

    , "remote_encoding": "GBK"

}
```


---

### option 2 - uncomment last

Yet another option is to put something you wouldn't comment out at the end of the file. Perhaps "connect_timeout"
```
{
    //"keepalive": 120,
    //...
    "remote_encoding": "GBK",
    //"allow_config_upload": false,
    "connect_timeout": 30
}
```
result
```json
{


    "remote_encoding": "GBK",

    "connect_timeout": 30
}
```

**Comment by luojianet** [comment]
my npm moudule [https://github.com/luojianet/demoSite/blob/master/npm-module/builder/builder.js#L255](builder) require strip-json-comments,use for analyze user project folder's sftp-config.json file,i can not change user json file。use[https://github.com/luojianet/demoSite/blob/master/npm-module/remove-json-comments/main.js](remove-json-comments) solve problem,thx your time.

**Comment by luojianet** [comment]
> I would not consider this a bug with `strip-json-comments`.
> 
> ### option 1 - leading commas
> Another option is to use leading commas.
> 
> ```
> {
>     "connect_timeout": 30
>     //, "keepalive": 120
>     , "remote_encoding": "GBK"
>     //, "allow_config_upload": false
> }
> ```
> result:
> 
> ```json
> {
>     "connect_timeout": 30
> 
>     , "remote_encoding": "GBK"
> 
> }
> ```
> 
> ### option 2 - uncomment last
> Yet another option is to put something you wouldn't comment out at the end of the file. Perhaps "connect_timeout"
> 
> ```
> {
>     //"keepalive": 120,
>     //...
>     "remote_encoding": "GBK",
>     //"allow_config_upload": false,
>     "connect_timeout": 30
> }
> ```
> result
> 
> ```json
> {
> 
> 
>     "remote_encoding": "GBK",
> 
>     "connect_timeout": 30
> }
> ```
my npm moudule [https://github.com/luojianet/demoSite/blob/master/npm-module/builder/builder.js#L255](builder) require strip-json-comments,use for analyze user project folder's sftp-config.json file,i can not change user json file。use[https://github.com/luojianet/demoSite/blob/master/npm-module/remove-json-comments/main.js](remove-json-comments) solve problem,thx your time.
