### ISSUE TITLE
UMD ES5 format for browser use?

### ISSUE THREAD

**Issue by Spiralis** [sindresorhus/strip-json-comments#42]
Could the library be made to support ES5, you think?

**Comment by sindresorhus** [comment]
This module mainly targets Node.js, not the browser. It's up to you to transpile it with Babel if you want to use it in the browser. You can find a more detailed explanation here: https://github.com/sindresorhus/ama/issues/446

If you use Webpack, check out [`babel-engine-plugin`](https://github.com/SamVerschueren/babel-engine-plugin), which transpiles only the dependencies that needs to be transpiled.

If you use Create React App, upgrade to [Create React App v2](https://reactjs.org/blog/2018/10/01/create-react-app-v2.html). It supports automatic transpilation of dependencies, which will make this package *just work*.

**Comment by Spiralis** [comment]
Ok, thanks. I'll check out your suggestions. In the meantime I have copied your sourcefile into my project, but added the MIT license at the top of the file. Is that ok for you?
