### ISSUE TITLE
the package is not compatible with ES6

### ISSUE THREAD

**Issue by eng-dibo** [sindresorhus/strip-json-comments#53]
```
require() of ES Module node_modules/strip-json-comments/index.js not supported.
Instead change the require of index.js to a dynamic import() which is available in all CommonJS modules
```

version: 4.0.0

**Comment by sindresorhus** [comment]
https://gist.github.com/sindresorhus/a39789f98801d908bbc7ff3ecc99d99c

**Comment by eng-dibo** [comment]
I updated the issue details with a minimal repo that follows the typical steps in [your link](https://gist.github.com/sindresorhus/a39789f98801d908bbc7ff3ecc99d99c)

**Comment by mrchantey** [comment]
Looks like the devs have decided to lock in ES6 only. For those looking for a similar utility package that still supports require, check out [jsonminify](https://www.npmjs.com/package/jsonminify).
