### ISSUE TITLE
support commonjs modules

### ISSUE THREAD

**Issue by eng-dibo** [sindresorhus/strip-json-comments#54]
not all modulaes that use strip-json-comments are migrated to esm, so you will need to support commonjs modules

this supporting is very easy
in your package.json
```
export:{
  import: './index.mjs',
  require: './index.cjs'
}
```

also, you will need to mention this breaking change in your docs, and confirm at  witch vision of `strip-json-comments` you migrated to esm, so (as a temporary workaround) other packages can downgrade to the older version of `strip-json-comments`

**Comment by sindresorhus** [comment]
https://gist.github.com/sindresorhus/a39789f98801d908bbc7ff3ecc99d99c

**Comment by eng-dibo** [comment]
> https://gist.github.com/sindresorhus/a39789f98801d908bbc7ff3ecc99d99c

this answer only forces developers to migrate their projects to use ESM which introduces breaking changes

alternatively, you should provide a hybrid package, make sense of using [conditional-exports](https://nodejs.org/api/packages.html#conditional-exports)

**details**
in your package.json use
```
 "exports": {
    "import": "./index.js",
    "require": "./index.cjs"
  },
```

and `index.cjs`  just includes the old syntax just before switching to ESM (i.e commonjs syntax)
