### ISSUE TITLE
update the document

### ISSUE THREAD

**Issue by eng-dibo** [sindresorhus/strip-json-comments#56]
as the author of this package doesn't want to make it hybrid, the document should be updated to indicate the correct version that should be used based on the module type.

> if your package is a commonjs module, you should use strip-json-comments < v4.0.0 or use [jsonminify](https://www.npmjs.com/package/jsonminify)
if you want to upgrade to >v4.0.0 you should [swich your project to esm](https://gist.github.com/sindresorhus/a39789f98801d908bbc7ff3ecc99d99c)

**Comment by sindresorhus** [comment]
I think it's expected knowledge to know what ESM is and how to handle it. It's also mentioned in the release notes.
