### ISSUE TITLE
Feature: strip trailing commas

### ISSUE THREAD

**Issue by cspotcode** [sindresorhus/strip-json-comments#57]
`tsconfig.json` supports comments but also trailing commas.  For example:

```
{
  "exclude": [], // trailing comma
}
```

It would be nice to have a flag that enables stripping of these trailing commas.

I bet we can do this by tracking the location of the most recently encountered comma, and detecting when we hit a `}` or `]`.  Both of those characters signal that the comma was trailing and can be either removed or replaced with a space.

This may add a tiny bit of complexity to the `result += ` statements.  Instead of `result +=`, we might want to do `accumulator +=` and then flush the accumulator to the result as soon as we have determined that the most recently-encountered comma is or is not trailing.  That way, `accumulator` will start where the comma is, and we'll have a good way to strip that comma if necessary.

I can probably attempt an implementation in the near-term.  My use-case requires CJS support, so I may do this in a fork, but I can at the very least share the patch here.

**Comment by sindresorhus** [comment]
I'm happy to see an option for this. 👍

**Comment by cspotcode** [comment]
Here is the implementation I came up with: cspotcode/strip-json-comments#1
