### ISSUE TITLE
[v4] SyntaxError: Unexpected token 'export'

### ISSUE THREAD

**Issue by pauldcomanici** [sindresorhus/strip-json-comments#58]
After installing `strip-json-comments` v4 I started to get
```
 export default function stripJsonComments(jsonString, {whitespace = true} = {}) {
    ^^^^^^

    SyntaxError: Unexpected token 'export'

    > 1 | import stripComments from 'strip-json-comments';
        |                                                 ^
```
See the pipeline: https://github.com/pauldcomanici/oia/runs/6077266927?check_suite_focus=true

This issue seems to be caused by the fact that the code is not transpiled to work inside NodeJs environment.

It is possible to add a transpiller step for this package?

**Comment by sindresorhus** [comment]
https://gist.github.com/sindresorhus/a39789f98801d908bbc7ff3ecc99d99c

**Comment by pauldcomanici** [comment]
Thank you.
