### ISSUE TITLE
The npm package supports `*.mjs`

### ISSUE THREAD

**Issue by RSS1102** [sindresorhus/strip-json-comments#62]
Can '*. mjs' output be supported within the published NPM package?
![image](https://github.com/sindresorhus/strip-json-comments/assets/81673017/4419adde-0998-4479-9140-46cd384e28de)

**Comment by sindresorhus** [comment]
It's an ESM package by other means: https://github.com/sindresorhus/strip-json-comments/blob/85611bf8a07246bca27f949c997a1460c57bbe9f/package.json#L13
